version: '20.10'
services:
  redis:
    image: redis:7.0.5
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 6379

  api:
    build: .
    container_name: api
    restart: unless-stopped
    network_mode: bridge
    command: /bin/sh -c 'nodemon -e js,html server.js'
    ports:
      - 8080:9000
    volumes:
      - .:/src
      - /src/node_modules

    links:
      - redis
